import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1777213841635 implements MigrationInterface {
    name = 'InitSchema1777213841635'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP CONSTRAINT "transaction_items_service_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP CONSTRAINT "transaction_items_staff_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP CONSTRAINT "transaction_items_transaction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_appointment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_salon_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "staffs_salon_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP CONSTRAINT "salons_owner_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP CONSTRAINT "service_categories_salon_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_salon_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "appointment_services_appointment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "appointment_services_service_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_customer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_salon_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_staff_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_items_trans"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_items_staff"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transactions_appointment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transactions_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transactions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staffs_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_salons_owner"`);
        await queryRunner.query(`DROP INDEX "public"."idx_service_categories_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_staff"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "valid_payment_method"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "valid_status"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "advance_booking"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "auto_confirm"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP CONSTRAINT "transaction_items_pkey"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD CONSTRAINT "PK_ff5a487ad820dccafd53bebf578" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "transaction_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "transaction_id" integer`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "service_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "service_id" integer`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "staff_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "staff_id" integer`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "service_name"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "service_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_pkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "appointment_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "appointment_id" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "salon_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "payment_method" character varying NOT NULL DEFAULT 'cash'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "paid_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "paid_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "staffs_pkey"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "PK_f3fec5e06209b46afdf8accf117" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "salon_id" integer`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "pin_code"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "pin_code" character varying`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "color" character varying`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "role" character varying NOT NULL DEFAULT 'junior'`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "commission_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" DROP CONSTRAINT "salons_pkey"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" ADD CONSTRAINT "PK_4cbe0adde860abd3b68b196a0b2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "owner_id"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "owner_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "logo_url" character varying`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "opening_time"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "opening_time" character varying NOT NULL DEFAULT '09:00'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "closing_time"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "closing_time" character varying NOT NULL DEFAULT '20:00'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "timezone" character varying NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "currency" character varying NOT NULL DEFAULT 'VND'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP CONSTRAINT "service_categories_pkey"`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD CONSTRAINT "PK_fe4da5476c4ffe5aa2d3524ae68" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "salon_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "color" character varying NOT NULL DEFAULT '#FF6B9D'`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_pkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "salon_id" integer`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "category_id" integer`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "color" character varying`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP CONSTRAINT "owners_pkey"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" ADD CONSTRAINT "PK_42838282f2e6b216301a70b02d6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP CONSTRAINT "owners_phone_key"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" ADD CONSTRAINT "UQ_f9635fa45f0cc7d71023abb3307" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "salon_name"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "salon_name" character varying`);
        await queryRunner.query(`ALTER TABLE "owners" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "customers_pkey"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "customers_phone_key"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "total_visits" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "total_spent"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "total_spent" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "appointment_services_pkey"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "PK_8423f59b66c157533b4df8b0459" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "appointment_id"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "appointment_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "service_id"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "service_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_pkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "staff_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "staff_id" integer`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "scheduled_date" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "start_time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "end_time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "status" character varying NOT NULL DEFAULT 'confirmed'`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "source" character varying NOT NULL DEFAULT 'walk_in'`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD CONSTRAINT "FK_5926425896b30c0d681fe879af0" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD CONSTRAINT "FK_7c812f276a22da3f81862e1d6bb" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_1f8d1173481678a035b4a81a4ec" FOREIGN KEY ("category_id") REFERENCES "service_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "FK_923e323e598280a0454e1d1b7cf" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "FK_5aafcd787c270f1fd2e01376a6b" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_d211f77ba4a4f32903f0fb73a75" FOREIGN KEY ("staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_2be3c78815aba227af1c3e8e413" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_2be3c78815aba227af1c3e8e413"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_d211f77ba4a4f32903f0fb73a75"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "FK_5aafcd787c270f1fd2e01376a6b"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "FK_923e323e598280a0454e1d1b7cf"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_1f8d1173481678a035b4a81a4ec"`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP CONSTRAINT "FK_7c812f276a22da3f81862e1d6bb"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP CONSTRAINT "FK_5926425896b30c0d681fe879af0"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "source" text DEFAULT 'walk_in'`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "status" text DEFAULT 'confirmed'`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "end_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "start_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "scheduled_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "staff_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "staff_id" bigint`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "customer_id" bigint`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "service_id"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "service_id" bigint`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "appointment_id"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "appointment_id" bigint`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "PK_8423f59b66c157533b4df8b0459"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "appointment_services_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "total_spent"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "total_spent" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "total_visits" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "phone" text`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "customers_phone_key" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_133ec679a801fab5e070f73d3ea"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "owners" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "salon_name"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "salon_name" text`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "password" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP CONSTRAINT "UQ_f9635fa45f0cc7d71023abb3307"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "phone" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" ADD CONSTRAINT "owners_phone_key" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" DROP CONSTRAINT "PK_42838282f2e6b216301a70b02d6"`);
        await queryRunner.query(`ALTER TABLE "owners" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "owners" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "owners" ADD CONSTRAINT "owners_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "color" text DEFAULT '#FF6B9D'`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "category_id" bigint`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "salon_id" bigint`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "color" text NOT NULL DEFAULT '#FF6B9D'`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "salon_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP CONSTRAINT "PK_fe4da5476c4ffe5aa2d3524ae68"`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD CONSTRAINT "service_categories_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "currency" text NOT NULL DEFAULT 'VND'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "timezone" text NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "closing_time"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "closing_time" TIME NOT NULL DEFAULT '20:00:00'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "opening_time"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "opening_time" TIME NOT NULL DEFAULT '09:00:00'`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "logo_url" text`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "city" text`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "phone" text`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "owner_id"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "owner_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" DROP CONSTRAINT "PK_4cbe0adde860abd3b68b196a0b2"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salons" ADD CONSTRAINT "salons_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "commission_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "role" text DEFAULT 'junior'`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "color" text DEFAULT '#FF6B9D'`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "pin_code"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "pin_code" text`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "phone" text`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "salon_id" bigint`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "PK_f3fec5e06209b46afdf8accf117"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "staffs_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "paid_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "paid_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "status" text NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "payment_method" text NOT NULL DEFAULT 'cash'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "salon_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "salon_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "appointment_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "appointment_id" bigint`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "service_name"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "service_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "staff_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "staff_id" bigint`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "service_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "service_id" bigint`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "transaction_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "transaction_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP CONSTRAINT "PK_ff5a487ad820dccafd53bebf578"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD CONSTRAINT "transaction_items_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "salon_id" bigint`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "auto_confirm" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "advance_booking" integer NOT NULL DEFAULT '30'`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "salons" ADD "website" text`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "valid_status" CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'cancelled'::text])))`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "valid_payment_method" CHECK ((payment_method = ANY (ARRAY['cash'::text, 'card'::text, 'transfer'::text, 'mixed'::text])))`);
        await queryRunner.query(`CREATE INDEX "idx_appointments_staff" ON "appointments" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_date" ON "appointments" ("scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_salon" ON "appointments" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_services_salon" ON "services" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_services_category" ON "services" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_service_categories_salon" ON "service_categories" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_salons_owner" ON "salons" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_staffs_salon" ON "staffs" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_transactions_status" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_transactions_salon" ON "transactions" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_transactions_appointment" ON "transactions" ("appointment_id") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_items_staff" ON "transaction_items" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_items_trans" ON "transaction_items" ("transaction_id") `);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "appointment_services_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "appointment_services_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "service_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD CONSTRAINT "service_categories_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salons" ADD CONSTRAINT "salons_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "staffs_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD CONSTRAINT "transaction_items_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD CONSTRAINT "transaction_items_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_items" ADD CONSTRAINT "transaction_items_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
