import { MigrationInterface, QueryRunner } from "typeorm";

export class EntityImprovements1777815324418 implements MigrationInterface {
    name = 'EntityImprovements1777815324418'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "loyalty_transactions_customer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "loyalty_transactions_salon_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "loyalty_transactions_transaction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_appointment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_customer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_salon_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loyalty_transactions_customer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loyalty_transactions_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_customer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_salon"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_scheduled"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "assigned_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "started_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "started_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "completed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "subtotal" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "discount_value" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "discount_amount" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "tax_rate" TYPE numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "tax_amount" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "tip_amount" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "total_amount" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "clock_in"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "clock_in" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "clock_out"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "clock_out" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ALTER COLUMN "hours_worked" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "salon_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "commission_rate" TYPE numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "shifts" ALTER COLUMN "safe_drop_total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "price" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "start_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "end_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payrolls" ALTER COLUMN "commission_amount" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "payrolls" ALTER COLUMN "tip_amount" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "payrolls" ALTER COLUMN "total_amount" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP COLUMN "paid_at"`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD "paid_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "total_spent"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "total_spent" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "loyalty_points"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "loyalty_points" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "loyalty_tier"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "loyalty_tier" character varying`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ALTER COLUMN "balance" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD "reason" character varying`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "scheduled_date" date`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "total_price" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "channel" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "error"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "error" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_6f09843c214f21a462b54b11e8" ON "transactions" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8d3ae44663921129bda4dcf6d" ON "transactions" ("shift_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c09d54644d40718fb05980f350" ON "transactions" ("appointment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_be3b7be565f8b9715107f902b7" ON "transactions" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dbc724f65b8a4ec283c3edebbe" ON "staffs" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f8d1173481678a035b4a81a4e" ON "services" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b89e2f1282797ad86a56ef926e" ON "services" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cf820a4a5b3b8ed6a1324416b" ON "customers" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d211f77ba4a4f32903f0fb73a7" ON "appointments" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2be3c78815aba227af1c3e8e41" ON "appointments" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f57af43f6cea76c5c4478eb133" ON "appointments" ("salon_id") `);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_39f39219f9587d34638ccde8b67" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_4b8298bcd10e67d31dc8d2e35b1" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9e2d01428faefb60e63c287c04a" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_b55350bc786b052e8523f313b9a" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4996a3ed0153ea116a71aec6d6f" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4996a3ed0153ea116a71aec6d6f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_b55350bc786b052e8523f313b9a"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9e2d01428faefb60e63c287c04a"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_4b8298bcd10e67d31dc8d2e35b1"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_39f39219f9587d34638ccde8b67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f57af43f6cea76c5c4478eb133"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2be3c78815aba227af1c3e8e41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d211f77ba4a4f32903f0fb73a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cf820a4a5b3b8ed6a1324416b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b89e2f1282797ad86a56ef926e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f8d1173481678a035b4a81a4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbc724f65b8a4ec283c3edebbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be3b7be565f8b9715107f902b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c09d54644d40718fb05980f350"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8d3ae44663921129bda4dcf6d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f09843c214f21a462b54b11e8"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "error"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "error" text`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "status" character varying(50) DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "channel" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'confirmed'`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "total_price" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "scheduled_date" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD "reason" text`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ALTER COLUMN "balance" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "loyalty_tier"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "loyalty_tier" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "loyalty_points"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "loyalty_points" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "total_spent"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "total_spent" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP COLUMN "paid_at"`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD "paid_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payrolls" ALTER COLUMN "total_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "payrolls" ALTER COLUMN "tip_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "payrolls" ALTER COLUMN "commission_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "end_time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "start_time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "price" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "shifts" ALTER COLUMN "safe_drop_total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "commission_rate" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "staffs" ALTER COLUMN "salon_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ALTER COLUMN "hours_worked" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "clock_out"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "clock_out" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "time_clocks" DROP COLUMN "clock_in"`);
        await queryRunner.query(`ALTER TABLE "time_clocks" ADD "clock_in" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "total_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "tip_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "tax_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "tax_rate" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "discount_amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "discount_value" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "subtotal" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "completed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "started_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "started_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waiting_list" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "waiting_list" ADD "assigned_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_scheduled" ON "notifications" ("scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_status" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_salon" ON "notifications" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_customer" ON "notifications" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_loyalty_transactions_salon" ON "loyalty_transactions" ("salon_id") `);
        await queryRunner.query(`CREATE INDEX "idx_loyalty_transactions_customer" ON "loyalty_transactions" ("customer_id") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_salon_id_fkey" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
